services:
  backend:
    build: ./server
    restart: always
    expose:
      - "8080" # Dùng expose thay vì ports để chỉ container nội bộ thấy nhau
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=quiz

  user:
    build: ./client
    restart: always
    expose:
      - "3001"

  admin:
    build: ./admin
    restart: always
    expose:
      - "3000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz
    volumes:
      - ./mysql.init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  # THÊM NGINX VÀO ĐÂY
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Đọc SSL từ máy thật
    depends_on:
      - backend
      - user
      - admin

volumes:
  db-data:
