spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/quiz?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Ho_Chi_Minh}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://quizvnua.com,https://www.quizvnua.com,https://admin.quizvnua.com}
app.cookie.domain=${APP_COOKIE_DOMAIN:.quizvnua.com}
app.cookie.secure=${APP_COOKIE_SECURE:true}
app.cookie.same-site=${APP_COOKIE_SAME_SITE:None}
app.cookie.max-age=${APP_COOKIE_MAX_AGE:86400}
