spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/quiz?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Ho_Chi_Minh}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
app.cookie.domain=${APP_COOKIE_DOMAIN:}
app.cookie.secure=${APP_COOKIE_SECURE:false}
app.cookie.same-site=${APP_COOKIE_SAME_SITE:Strict}
app.cookie.max-age=${APP_COOKIE_MAX_AGE:86400}
