# ====================================================================
# RabbitMQ Configuration & Branding - Quiz VNUA
# ====================================================================

# Ten dinh danh Cluster hien thi tren he thong
cluster_name = Quiz VNUA Message Broker

