# ====================================================================
# RabbitMQ Configuration & Branding - Quiz VNUA
# ====================================================================

# Ten dinh danh Cluster hien thi tren he thong
cluster_name = Quiz VNUA Message Broker

# Tieu de hien thi tren thanh Header cua giao dien Web Management
management.header = Quiz VNUA - He Thong Hang Doi
